chore: Update build command and install dependencies in node.js.yml workflow

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -8,16 +8,19 @@ jobs:
     steps:
       - checkout
       - run:
+          name: Install Dependencies
+          command: npm install
+      - run:
           name: Start and Verify
           command: |
             npm start > start.log 2>&1 &
-             sleep 5
-             if grep -q "config.json file does not exist. Read the installation/setup instructions." start.log; then
-               echo "Build and start completed successfully!"
-               exit 0
-             else
-               echo "An unexpected error occurred!"
-               exit 1
+            sleep 5
+            if grep -q "config.json file does not exist. Read the installation/setup instructions." start.log; then
+              echo "Build and start completed successfully!"
+              exit 0
+            else
+              echo "An unexpected error occurred!"
+              exit 1
   test-v10:
     docker:
       - image: cimg/base:stable
@@ -26,16 +29,19 @@ jobs:
       - node/install:
           node-version: "10.24"
       - run:
+          name: Install Dependencies
+          command: npm install
+      - run:
           name: Start and Verify
           command: |
             npm start > start.log 2>&1 &
-             sleep 5
-             if grep -q "config.json file does not exist. Read the installation/setup instructions." start.log; then
-               echo "Build and start completed successfully!"
-               exit 0
-             else
-               echo "An unexpected error occurred!"
-               exit 1
+            sleep 5
+            if grep -q "config.json file does not exist. Read the installation/setup instructions." start.log; then
+              echo "Build and start completed successfully!"
+              exit 0
+            else
+              echo "An unexpected error occurred!"
+              exit 1
   test-v12:
     docker:
       - image: cimg/base:stable
@@ -44,16 +50,19 @@ jobs:
       - node/install:
           node-version: "12.22"
       - run:
+          name: Install Dependencies
+          command: npm install
+      - run:
           name: Start and Verify
           command: |
             npm start > start.log 2>&1 &
-             sleep 5
-             if grep -q "config.json file does not exist. Read the installation/setup instructions." start.log; then
-               echo "Build and start completed successfully!"
-               exit 0
-             else
-               echo "An unexpected error occurred!"
-               exit 1
+            sleep 5
+            if grep -q "config.json file does not exist. Read the installation/setup instructions." start.log; then
+              echo "Build and start completed successfully!"
+              exit 0
+            else
+              echo "An unexpected error occurred!"
+              exit 1
   test-v14:
     docker:
       - image: cimg/base:stable
@@ -62,16 +71,19 @@ jobs:
       - node/install:
           node-version: "14.21"
       - run:
+          name: Install Dependencies
+          command: npm install
+      - run:
           name: Start and Verify
           command: |
             npm start > start.log 2>&1 &
-             sleep 5
-             if grep -q "config.json file does not exist. Read the installation/setup instructions." start.log; then
-               echo "Build and start completed successfully!"
-               exit 0
-             else
-               echo "An unexpected error occurred!"
-               exit 1
+            sleep 5
+            if grep -q "config.json file does not exist. Read the installation/setup instructions." start.log; then
+              echo "Build and start completed successfully!"
+              exit 0
+            else
+              echo "An unexpected error occurred!"
+              exit 1
   test-v16:
     docker:
       - image: cimg/base:stable
@@ -80,16 +92,19 @@ jobs:
       - node/install:
           node-version: "16.20"
       - run:
+          name: Install Dependencies
+          command: npm install
+      - run:
           name: Start and Verify
           command: |
             npm start > start.log 2>&1 &
-             sleep 5
-             if grep -q "config.json file does not exist. Read the installation/setup instructions." start.log; then
-               echo "Build and start completed successfully!"
-               exit 0
-             else
-               echo "An unexpected error occurred!"
-               exit 1
+            sleep 5
+            if grep -q "config.json file does not exist. Read the installation/setup instructions." start.log; then
+              echo "Build and start completed successfully!"
+              exit 0
+            else
+              echo "An unexpected error occurred!"
+              exit 1
   test-v18:
     docker:
       - image: cimg/base:stable
@@ -98,16 +113,19 @@ jobs:
       - node/install:
           node-version: "18.20"
       - run:
+          name: Install Dependencies
+          command: npm install
+      - run:
           name: Start and Verify
           command: |
             npm start > start.log 2>&1 &
-             sleep 5
-             if grep -q "config.json file does not exist. Read the installation/setup instructions." start.log; then
-               echo "Build and start completed successfully!"
-               exit 0
-             else
-               echo "An unexpected error occurred!"
-               exit 1
+            sleep 5
+            if grep -q "config.json file does not exist. Read the installation/setup instructions." start.log; then
+              echo "Build and start completed successfully!"
+              exit 0
+            else
+              echo "An unexpected error occurred!"
+              exit 1
   test-v20:
     docker:
       - image: cimg/base:stable
@@ -116,15 +134,19 @@ jobs:
       - node/install:
           node-version: "20.18"
       - run:
+          name: Install Dependencies
+          command: npm install
+      - run:
+          name: Start and Verify
           command: |
             npm start > start.log 2>&1 &
-             sleep 5
-             if grep -q "config.json file does not exist. Read the installation/setup instructions." start.log; then
-               echo "Build and start completed successfully!"
-               exit 0
-             else
-               echo "An unexpected error occurred!"
-               exit 1
+            sleep 5
+            if grep -q "config.json file does not exist. Read the installation/setup instructions." start.log; then
+              echo "Build and start completed successfully!"
+              exit 0
+            else
+              echo "An unexpected error occurred!"
+              exit 1
   test-v22:
     docker:
       - image: cimg/base:stable
@@ -132,6 +154,9 @@ jobs:
       - checkout
       - node/install:
           node-version: "22.11"
+      - run:
+          name: Install Dependencies
+          command: npm install
       - run:
           name: Start and Verify
           command: |
