chore: Update build command in node.js.yml workflow

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -11,17 +11,13 @@ jobs:
           name: Start and Verify
           command: |
             npm start > start.log 2>&1 &
-            START_PID=$!
-            sleep 5
-            if grep -q "config.json file does not exist. Read the installation/setup instructions." start.log; then
-              echo "Build and start completed successfully!"
-              kill $START_PID
-              exit 0
-            else
-              echo "An unexpected error occurred!"
-            fi
-            kill $START_PID
-            exit 1
+             sleep 5
+             if grep -q "config.json file does not exist. Read the installation/setup instructions." start.log; then
+               echo "Build and start completed successfully!"
+               exit 0
+             else
+               echo "An unexpected error occurred!"
+               exit 1
   test-v10:
     docker:
       - image: cimg/base:stable
@@ -33,17 +29,13 @@ jobs:
           name: Start and Verify
           command: |
             npm start > start.log 2>&1 &
-            START_PID=$!
-            sleep 5
-            if grep -q "config.json file does not exist. Read the installation/setup instructions." start.log; then
-              echo "Build and start completed successfully!"
-              kill $START_PID
-              exit 0
-            else
-              echo "An unexpected error occurred!"
-            fi
-            kill $START_PID
-            exit 1
+             sleep 5
+             if grep -q "config.json file does not exist. Read the installation/setup instructions." start.log; then
+               echo "Build and start completed successfully!"
+               exit 0
+             else
+               echo "An unexpected error occurred!"
+               exit 1
   test-v12:
     docker:
       - image: cimg/base:stable
@@ -55,17 +47,13 @@ jobs:
           name: Start and Verify
           command: |
             npm start > start.log 2>&1 &
-            START_PID=$!
-            sleep 5
-            if grep -q "config.json file does not exist. Read the installation/setup instructions." start.log; then
-              echo "Build and start completed successfully!"
-              kill $START_PID
-              exit 0
-            else
-              echo "An unexpected error occurred!"
-            fi
-            kill $START_PID
-            exit 1
+             sleep 5
+             if grep -q "config.json file does not exist. Read the installation/setup instructions." start.log; then
+               echo "Build and start completed successfully!"
+               exit 0
+             else
+               echo "An unexpected error occurred!"
+               exit 1
   test-v14:
     docker:
       - image: cimg/base:stable
@@ -77,17 +65,13 @@ jobs:
           name: Start and Verify
           command: |
             npm start > start.log 2>&1 &
-            START_PID=$!
-            sleep 5
-            if grep -q "config.json file does not exist. Read the installation/setup instructions." start.log; then
-              echo "Build and start completed successfully!"
-              kill $START_PID
-              exit 0
-            else
-              echo "An unexpected error occurred!"
-            fi
-            kill $START_PID
-            exit 1
+             sleep 5
+             if grep -q "config.json file does not exist. Read the installation/setup instructions." start.log; then
+               echo "Build and start completed successfully!"
+               exit 0
+             else
+               echo "An unexpected error occurred!"
+               exit 1
   test-v16:
     docker:
       - image: cimg/base:stable
@@ -99,17 +83,13 @@ jobs:
           name: Start and Verify
           command: |
             npm start > start.log 2>&1 &
-            START_PID=$!
-            sleep 5
-            if grep -q "config.json file does not exist. Read the installation/setup instructions." start.log; then
-              echo "Build and start completed successfully!"
-              kill $START_PID
-              exit 0
-            else
-              echo "An unexpected error occurred!"
-            fi
-            kill $START_PID
-            exit 1
+             sleep 5
+             if grep -q "config.json file does not exist. Read the installation/setup instructions." start.log; then
+               echo "Build and start completed successfully!"
+               exit 0
+             else
+               echo "An unexpected error occurred!"
+               exit 1
   test-v18:
     docker:
       - image: cimg/base:stable
@@ -121,17 +101,13 @@ jobs:
           name: Start and Verify
           command: |
             npm start > start.log 2>&1 &
-            START_PID=$!
-            sleep 5
-            if grep -q "config.json file does not exist. Read the installation/setup instructions." start.log; then
-              echo "Build and start completed successfully!"
-              kill $START_PID
-              exit 0
-            else
-              echo "An unexpected error occurred!"
-            fi
-            kill $START_PID
-            exit 1
+             sleep 5
+             if grep -q "config.json file does not exist. Read the installation/setup instructions." start.log; then
+               echo "Build and start completed successfully!"
+               exit 0
+             else
+               echo "An unexpected error occurred!"
+               exit 1
   test-v20:
     docker:
       - image: cimg/base:stable
@@ -142,17 +118,13 @@ jobs:
       - run:
           command: |
             npm start > start.log 2>&1 &
-            START_PID=$!
-            sleep 5
-            if grep -q "config.json file does not exist. Read the installation/setup instructions." start.log; then
-              echo "Build and start completed successfully!"
-              kill $START_PID
-              exit 0
-            else
-              echo "An unexpected error occurred!"
-            fi
-            kill $START_PID
-            exit 1
+             sleep 5
+             if grep -q "config.json file does not exist. Read the installation/setup instructions." start.log; then
+               echo "Build and start completed successfully!"
+               exit 0
+             else
+               echo "An unexpected error occurred!"
+               exit 1
   test-v22:
     docker:
       - image: cimg/base:stable
@@ -164,17 +136,13 @@ jobs:
           name: Start and Verify
           command: |
             npm start > start.log 2>&1 &
-            START_PID=$!
             sleep 5
             if grep -q "config.json file does not exist. Read the installation/setup instructions." start.log; then
               echo "Build and start completed successfully!"
-              kill $START_PID
               exit 0
             else
               echo "An unexpected error occurred!"
-            fi
-            kill $START_PID
-            exit 1
+              exit 1
 workflows:
   build_and_test:
     jobs:
